### ISSUE TITLE
chapter02 docker-compose error

### ISSUE THREAD

**Issue by mutomasa** [PacktPublishing/Cloud-Native-Observability#16]
**docker-compose up Error Message**
ERROR: for opentelemetry-collector  Cannot create container for service opentelemetry-collector: json: cannot unmarshal number 0.1 into Go struct field ContainerConfigWrapper.StopTimeout of type int
ERROR: compose.cli.main.exit_with_metrics: Encountered errors while bringing up the project.

**docker-compose --version**
docker-compose version 1.29.2, build unknown

**Comment by qdzlug** [comment]
Seeing the same error:

```
ERROR: for opentelemetry-collector  Cannot create container for service opentelemetry-collector: json: cannot unmarshal number 0.1 into Go struct field ContainerConfigWrapper.StopTimeout of type int
ERROR: Encountered errors while bringing up the project.
❯ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```

Doing a little digging, if you run the image w/o the included configuration it comes up without issues. So something in the configuration is causing this issue. Will dig more later, time permitting.

**Comment by qdzlug** [comment]
Good news and bad news....

The good news is that I've tracked the issue to the `stop_grace_period: 100ms` lines in the compose file. If you remove these, it should allow everything to come up as expected.

The bad news is that I have no idea why this is the case - that directive *should* work based on some research.

**Comment by mutomasa** [comment]
@qdzlug 
Thank you for leading me to solving the issues.
everything is up as expected.

**Comment by qdzlug** [comment]
@mutomasa - no worries, glad it's working. 

Based on https://docs.docker.com/compose/compose-file/compose-file-v3/#stop_grace_period the directive takes a duration argument, but the duration argument doesn't seem to accept `ms` as a unit, only `h`, `m`, `s`:  https://docs.docker.com/compose/compose-file/compose-file-v3/#specifying-durations

So I wager that changing it to `stop_grace_period: 0.1s` will likely solve the problem and keep the intended grace period. I'll check that later this weekend and open a PR if that does indeed fix it.

**Comment by mutomasa** [comment]
@qdzlug 
Thank you for the docker doc link.
I am a bit suprised not to accept the duration unit "ms". 
so I inderstand you changed it to stop_grace_period: 0.1s.

**Comment by qdzlug** [comment]
@mutomasa - no, I actually had to change it to `1s` - if you look at the error it's being converted to `0.1s` and that is what is failing with the error about the `int` variable type.

**Comment by codeboten** [comment]
Thanks for reporting this, I'm also surprised to see this didn't work as expected in older versions of docker compose, since according to the docs it uses durations, which according to the examples [here](https://docs.docker.com/compose/compose-file/compose-file-v3/#specifying-durations) support ms. 1s duration is ok as well, I'm happy to accept the PR.

**Comment by codeboten** [comment]
Closing as the PR has been merged. Thanks again!
