### ISSUE TITLE
macos monterry: port 5000 in use by airplay receiver

### ISSUE THREAD

**Issue by qdzlug** [PacktPublishing/Cloud-Native-Observability#18]
Less of an issue and more of an FYI....

In case others hit this problem and are not aware, port 5000 is now in use by airplay receiver in this version of MacOS. One can only assume nobody at Apple uses Flask? 

The easiest fix is to use a different port. However, you can also go into the sharing systems preference and uncheck the airplay receiver.

More detail here: https://medium.com/pythonistas/port-5000-already-in-use-macos-monterey-issue-d86b02edd36c

**Comment by emilyashley** [comment]
Thank you for this! I got stuck on this for a moment and now I'm unblocked :)

**Comment by codeboten** [comment]
Thanks for reporting! I've added it to the troubleshooting document: https://github.com/PacktPublishing/Cloud-Native-Observability/blob/main/TROUBLESHOOTING.md#port-5000-in-use-by-airplay-receiver
