### ISSUE TITLE
troubleshooting chapter08 with opentelemetry-sdk 1.12.0 and opentelemetry-exporter-otlp 1.12.0

### ISSUE THREAD

**Issue by emilyashley** [PacktPublishing/Cloud-Native-Observability#20]
Hello 👋 just adding a friendly note here that if you're also running the book examples with the latest OTel libraries (1.12.0 as opposed to 1.9.0 in the book) you may need to make some quick changes

in common.py change:
-  `from opentelemetry.sdk._logs import OTLPHandler` is now `LoggingHandler`
- `from opentelemetry.exporter.otlp.proto.grpc._metric_exporter` is now `from opentelemetry.exporter.otlp.proto.grpc.metric_exporter`

in grocery_store.py, also change references of `OTLPHandler` to `LoggingHandler`

**Comment by dgoscn** [comment]
Thanks @emilyashley

**Comment by nithikpackt** [comment]
Thank you @emilyashley .Closing the issue.
