### ISSUE TITLE
Images for Mac M1

### ISSUE THREAD

**Issue by janssenlima** [PacktPublishing/Cloud-Native-Observability#21]
Could you make the images available for arm architecture (Mac M1)?
In chapter 2 the shopper, grocery-store and legacy-inventory images are not running in my environment.

**Comment by janssenlima** [comment]
Resolved by increasing the memory limit on grocery-store and legacy-inventory services.

**Comment by dbuls** [comment]
Just to add to this, on a MacBook Pro 14" M1, I had to bump the  'memory limit' for `grocery-store` and `legacy-inventory` services to `200M` for it to work, otherwise the containers would exit with `137`.
