### ISSUE TITLE
/usr/bin/env: ‘python3\r’: No such file or directory in chapter03

### ISSUE THREAD

**Issue by mgvinuesa** [PacktPublishing/Cloud-Native-Observability#22]
Hello,

Only to know, I just execute the _chapter03_ on Windows with WSL (Ubuntu) and I have this error when trying to start the **brokentelephone-python** container.

`/usr/bin/env: ‘python3\r’: No such file or directory
`

I have had to execute dos2unix command in the docker-compose file and python files to change the ending characters and rebuild again and its works.

**Comment by nithikpackt** [comment]
Thank you @mgvinuesa  for the solution. Closing the issue now.
